site_name: GoToSocial Documentation
site_url: https://docs.gotosocial.org
theme:
  name: material
  language: en
  font: false
  features:
    - header.autohide
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
repo_url: https://github.com/superseriousbusiness/gotosocial
edit_uri: edit/main/docs/
copyright: GoToSocial is licensed under the GNU AGPL v3 LICENSE. Copyright (C) GoToSocial Authors admin@gotosocial.org
plugins:
  - search:
      lang: en
  - social:
      cards: true
      cards_layout_options:
        background_color: "#fd6a00"
        color: "#fafaff"
      cache_dir: "./docs/.cache/plugin/social"
  - swagger-ui-tag:
      supportedSubmitMethods: []
      syntaxHighlightTheme: obsidian
  - include-markdown

extra_css:
  - assets/css/colours.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - "Home": "index.md"
  - "FAQ": "faq.md"
  - "User Guide":
      - "user_guide/settings.md"
      - "user_guide/posts.md"
      - "user_guide/search.md"
      - "user_guide/custom_css.md"
      - "user_guide/password_management.md"
      - "user_guide/rss.md"
      - "user_guide/migration.md"
  - "Getting Started":
      - "getting_started/index.md"
      - "getting_started/releases.md"
      - "Installation":
        - "getting_started/installation/index.md"
        - "getting_started/installation/metal.md"
        - "getting_started/installation/container.md"
      - "Reverse Proxy":
        - "getting_started/reverse_proxy/index.md"
        - "getting_started/reverse_proxy/nginx.md"
        - "getting_started/reverse_proxy/apache-httpd.md"
        - "getting_started/reverse_proxy/caddy.md"
        - "getting_started/reverse_proxy/websocket.md"
      - "getting_started/user_creation.md"
  - "Configuration":
      - "configuration/index.md"
      - "configuration/general.md"
      - "configuration/database.md"
      - "configuration/web.md"
      - "configuration/instance.md"
      - "configuration/accounts.md"
      - "configuration/media.md"
      - "configuration/storage.md"
      - "configuration/statuses.md"
      - "configuration/tls.md"
      - "configuration/oidc.md"
      - "configuration/smtp.md"
      - "configuration/syslog.md"
      - "configuration/httpclient.md"
      - "configuration/advanced.md"
      - "configuration/observability.md"
  - "Advanced":
    - "advanced/index.md"
    - "advanced/host-account-domain.md"
    - "advanced/outgoing-proxy.md"
    - "Caching":
      - "advanced/caching/index.md"
      - "advanced/caching/api.md"
      - "advanced/caching/assets-media.md"
    - "advanced/certificates.md"
    - "Enhanced security":
      - "advanced/security/index.md"
      - "advanced/security/sandboxing.md"
      - "advanced/security/firewall.md"
    - "advanced/healthchecks.md"
    - "advanced/tracing.md"
    - "advanced/metrics.md"
    - "advanced/replicating-sqlite.md"
    - "advanced/sqlite-networked-storage.md"

  - "Admin":
      - "admin/settings.md"
      - "admin/signups.md"
      - "admin/federation_modes.md"
      - "admin/domain_blocks.md"
      - "admin/request_filtering_modes.md"
      - "admin/robots.md"
      - "admin/cli.md"
      - "admin/backup_and_restore.md"
      - "admin/media_caching.md"
      - "admin/spam.md"
      - "admin/database_maintenance.md"
      - "admin/themes.md"
  - "Federation":
      - "federation/index.md"
      - "federation/http_signatures.md"
      - "federation/access_control.md"
      - "federation/ratelimiting.md"
      - "federation/actors.md"
      - "federation/posts.md"
      - "federation/moderation.md"
      - "federation/glossary.md"
  - "Client API Docs":
      - "api/authentication.md"
      - "api/swagger.md"
      - "api/ratelimiting.md"
      - "api/throttling.md"
