name: gotosocial-docs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py311h06a4308_0
  - python=3.11.3=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - beautifulsoup4==4.12.2
      - cairocffi==1.5.1
      - cairosvg==2.7.0
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - colorama==0.4.6
      - cssselect2==0.7.0
      - defusedxml==0.7.1
      - ghp-import==2.1.0
      - idna==3.4
      - jinja2==3.1.2
      - markdown==3.3.7
      - markupsafe==2.1.2
      - mergedeep==1.3.4
      - mkdocs==1.4.3
      - mkdocs-material==9.1.9
      - mkdocs-material-extensions==1.1.1
      - mkdocs-swagger-ui-tag==0.6.1
      - packaging==23.1
      - pillow==9.5.0
      - pycparser==2.21
      - pygments==2.15.1
      - pymdown-extensions==9.11
      - python-dateutil==2.8.2
      - pyyaml==6.0
      - pyyaml-env-tag==0.1
      - regex==2023.5.5
      - requests==2.30.0
      - six==1.16.0
      - soupsieve==2.4.1
      - tinycss2==1.2.1
      - urllib3==2.0.2
      - watchdog==3.0.0
      - webencodings==0.5.1
